=== SiteView/ECC8.13/trunk/java.prj/sv6.5/src/COM/dragonflow/ems/xmlMonitor/Monitor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Monitor" type="monitorType"/>
	<xs:complexType name="monitorType">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="ConfigFilePathProperty" type="configFilePathPropertyType"/>
			<xs:element name="TimeDiffProperty" type="timeDiffPropertyType"/>
			<xs:element name="MeasurementConfigFilePathProperty" type="configFilePathPropertyType"/>
			<xs:element name="StringProperty" type="stringPropertyType" maxOccurs="unbounded"/>
			<xs:element name="PasswordProperty" type="stringPropertyType" maxOccurs="unbounded"/>
			<xs:element name="HiddenStringProperty" type="hiddenStringPropertyType" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="IntProperty" type="intPropertyType" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="emsFolderName" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="hiddenPropertyType">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="isState" type="xs:boolean" use="optional"/>
	</xs:complexType>
	<xs:complexType name="hiddenStringPropertyType">
		<xs:complexContent>
			<xs:extension base="hiddenPropertyType">
				<xs:attribute name="value" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="intPropertyType">
		<xs:complexContent>
			<xs:extension base="propertyType">
				<xs:attribute name="value" type="xs:number" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="propertyType">
		<xs:attribute name="isAdvanced" type="xs:boolean" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="description" type="xs:string" use="required"/>
		<xs:attribute name="label" type="xs:string" use="required"/>
		<xs:attribute name="isEditable" type="xs:boolean" use="required"/>
		<xs:attribute name="stateOptions" type="xs:int" use="optional"/>
	</xs:complexType>
	<xs:complexType name="stringPropertyType">
		<xs:complexContent>
			<xs:extension base="propertyType">
				<xs:attribute name="value" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="filePathPropertyType">
		<xs:complexContent>
			<xs:extension base="propertyType">
				<xs:attribute name="value" type="xs:string" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="configFilePathPropertyType"/>
	<xs:complexType name="timeDiffPropertyType"/>
	<xs:complexType name="numericPropertyType">
		<xs:complexContent>
			<xs:extension base="propertyType">
				<xs:attribute name="value" type="xs:double" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== SiteView/ECC8.13/trunk/java.prj/sv65Ecc_ofbiz_component/resource/classes/com/dragonflow/topaz/ems/JDBCSource/db.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monitor name="db" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../ems/Monitor.xsd">
	<ConfigFilePathProperty/>
	<StringProperty isAdvanced="false" name="_database" isEditable="true" label="db_url_label" description="db_url_description" />
	<StringProperty isAdvanced="false" name="_driver" isEditable="true" label="driver_name_label" description="driver_name_description" />
	<StringProperty isAdvanced="false" name="_user" isEditable="true" label="db_user_name_label" description="db_user_name_description"/>
	<PasswordProperty isAdvanced="false" name="_password" isEditable="true" label="db_password_label" description="db_password_description"/>
	<StringProperty isAdvanced="false" name="_select" isEditable="true" label="db_select_label" description="db_select_description"/>
	<StringProperty isAdvanced="false" name="_from" isEditable="true" label="db_from_label" description="db_from_description"/>
	<StringProperty isAdvanced="false" name="_where" isEditable="true" label="db_where_label" description="db_where_description"/>
	<StringProperty isAdvanced="false" name="_orderby" isEditable="true" label="db_orderby_label" description="db_orderby_description"/>
	<StringProperty isAdvanced="false" name="_emsTablePrimaryKeys" isEditable="true" label="db_enum_field_label" description="db_enum_field_description"/>
	<StringProperty isAdvanced="false" name="_resetEmum" isEditable="true" label="db_enum_value_label" description="db_enum_value_description"/>
	
	<!--	
	public static final String OLD_DB_ENUM_FIELD_TYPE="_fieldType";-->
	<TimeDiffProperty/>
	<HiddenStringProperty name="lastEmum" value="-1"/>
	<IntProperty isAdvanced="false" name="pCollected" isEditable="false" value="0" stateOptions="1" label="title_collected_measurements" description="title_collected_measurements"/>
</Monitor>

=== SiteView/ECC8.13/trunk/java.prj/sv65Ecc_ofbiz_component/resource/classes/com/dragonflow/topaz/ems/arm/arm.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monitor name="arm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  emsFolderName="ApplicationRelationshipMappings"  xsi:noNamespaceSchemaLocation="../../../../../../../../ems/Monitor.xsd">
	<MeasurementConfigFilePathProperty/>
	<StringProperty isAdvanced="false" name="_pDbUrl" isEditable="true" label="db_url_arm_label" description="db_url_description" value="jdbc:inetora:&lt;host&gt;:1521:&lt;instance&gt;"/>
	<StringProperty isAdvanced="false" name="_pDbDriverName" isEditable="true" label="driver_name_label" description="driver_name_description" value="com.inet.ora.OraDriver"/>
	<StringProperty isAdvanced="false" name="_pDbUserName" isEditable="true" label="db_user_name_label" description="db_user_name_description"/>
	<PasswordProperty isAdvanced="false" name="_pDbPassword" isEditable="true" label="db_password_label" description="db_password_description"/>
	<TimeDiffProperty/>
	<HiddenStringProperty name="pStartTime" value="-1"/>
	<IntProperty isAdvanced="false" name="pCollected" isEditable="false" value="0" stateOptions="1" label="title_collected_measurements"/>
</Monitor>

=== SiteView/ECC8.13/trunk/java.prj/sv65Ecc_ofbiz_component/resource/classes/com/dragonflow/topaz/ems/cim/cim.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monitor name="cim" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  emsFolderName="CIM"  xsi:noNamespaceSchemaLocation="../../../../../../../../ems/Monitor.xsd">
	<ConfigFilePathProperty/>
	<StringProperty isAdvanced="false" name="_pDbUrl" isEditable="true" label="db_url_label" description="db_url_description" value="jdbc:inetdae:&lt;host&gt;:&lt;port&gt;?database=&lt;db_name&gt;"/>
	<StringProperty isAdvanced="false" name="_pDbDriverName" isEditable="true" label="driver_name_label" description="driver_name_description" value="com.inet.tds.TdsDriver"/>
	<StringProperty isAdvanced="false" name="_pDbUserName" isEditable="true" label="db_user_name_label" description="db_user_name_description"/>
	<PasswordProperty isAdvanced="false" name="_pDbPassword" isEditable="true" label="db_password_label" description="db_password_description"/>
	<TimeDiffProperty/>
	<HiddenStringProperty name="pStartTime" value="-1"/>
	<IntProperty isAdvanced="false" name="pCollected" isEditable="false" value="0" stateOptions="1" label="title_collected_measurements"/>
</Monitor>

=== SiteView/ECC8.13/trunk/java.prj/sv65Ecc_ofbiz_component/resource/classes/com/dragonflow/topaz/ems/concord/concord.xml
<?xml version="1.0" encoding="UTF-8"?>
<Monitor name="concord" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"   emsFolderName="concord"  xsi:noNamespaceSchemaLocation="../../../../../../../../ems/Monitor.xsd">
	<MeasurementConfigFilePathProperty/>
	<StringProperty isAdvanced="false" name="_pDbUrl" isEditable="true" label="db_url_concord_label" description="db_url_description"/>
	<StringProperty isAdvanced="false" name="_pDbDriverName" isEditable="true" label="driver_name_label" description="driver_name_description"/>
	<StringProperty isAdvanced="false" name="_pDbUserName" isEditable="true" label="db_user_name_label" description="db_user_name_description"/>
	<StringProperty isAdvanced="false" name="_pDbPassword" isEditable="true" label="db_password_label" description="db_password_description"/>
	<StringProperty isAdvanced="true" name="_pDbSelect" isEditable="true" label="db_select_label" description="db_select_description" value="*"/>
	<StringProperty isAdvanced="true" name="_pDbWhere" isEditable="true" label="db_where_label" description="db_where_description"/>
	<TimeDiffProperty/>
	<HiddenStringProperty name="pStartTime" value="-1"/>
	<IntProperty isAdvanced="false" name="pCollected" isEditable="false" value="0" stateOptions="1" label="title_collected_measurements"/>
</Monitor>
