=== SiteView/ECC8.13/trunk/java.prj/sv65Ecc_ofbiz_component/resource/templates.applications/conf_tree_1_0.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XML Spy v4.4 U (http://www.xmlspy.com)-->
<!ELEMENT calc (param*)>
<!ATTLIST calc
	calc_class_name CDATA #REQUIRED
	calc_start_level CDATA #REQUIRED
	calc_stop_level CDATA #IMPLIED
>
<!ELEMENT monitor EMPTY>
<!ATTLIST monitor
	monitor_type CDATA #REQUIRED
>
<!ELEMENT node (calc* | selector* | node* | param*)*>
<!ATTLIST node
	id CDATA #REQUIRED
>
<!ELEMENT param EMPTY>
<!ATTLIST param
	id CDATA #REQUIRED
	value CDATA #REQUIRED
	type CDATA #REQUIRED
>
<!ELEMENT root (tree*)>
<!ELEMENT selector EMPTY>
<!ATTLIST selector
	oper CDATA #REQUIRED
	key CDATA #REQUIRED
	value CDATA #IMPLIED
>
<!ELEMENT tree (monitor+, node*)>
<!ATTLIST tree
	aggregator_id CDATA #REQUIRED
	num_of_buckets CDATA #REQUIRED
	time_interval CDATA #REQUIRED
	timer CDATA #IMPLIED
>

=== SiteView/ECC8.13/trunk/java.prj/sv65Ecc_ofbiz_component/resource/templates.applications/J2EEAggregation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "conf_tree_1_0.dtd">
<root>

  <tree aggregator_id="SiteScopeAggregator" time_interval="15" num_of_buckets="2">
    <monitor monitor_type="J2EEMonitor"/>
    <node id="J2EE: %J2EE%" >
      <calc calc_class_name="com.mercury.topaz.j2ee.aggregator.EJBUpperLevelCalculator" calc_start_level="0" calc_stop_level="2"/>
      <node id="group: %group%">
        <node id="class: %class%">
          <node id="Method: %Method%">
            <calc calc_class_name="com.mercury.topaz.j2ee.aggregator.EJBIsTsMethodLevelCalculator" calc_start_level="0" calc_stop_level="0"/>
            <selector key="SQL" oper="exist"/>
            <node id="SQL: %SQL%">
              <calc calc_class_name="com.mercury.topaz.j2ee.aggregator.EJBSiteScopeSQLOverTimeCalculator" calc_start_level="0" calc_stop_level="0"/>
              <node id="%TimeStamp%">
                <calc calc_class_name="com.mercury.topaz.j2ee.aggregator.EJBTimeStampLevelCalculator" calc_start_level="0" calc_stop_level="0"/>
              </node>
            </node>
          </node>
          <node id="Method: %Method%">
            <calc calc_class_name="com.mercury.topaz.j2ee.aggregator.EJBIsTsMethodLevelCalculator" calc_start_level="0" calc_stop_level="0"/>
            <selector key="SQL" oper="not_exist"/>
            <node id="%TimeStamp%">
              <param id="TS" value="true" type="java.lang.Boolean"/>
              <calc calc_class_name="com.mercury.topaz.j2ee.aggregator.EJBTimeStampLevelCalculator" calc_start_level="0" calc_stop_level="0"/>
            </node>
          </node>
        </node>
      </node>
    </node>
  </tree>
</root>
